# Generated by Django 4.2.3 on 2023-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
